spring:
  application:
    name: fms

  datasource:
    url: jdbc:postgresql://localhost:5432/fms_dev
    username: fms
    password: fmspass

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

  flyway:
    enabled: true

server:
  port: 8080

app:
  jwt:
    secret: ${APP_JWT_SECRET:CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_CHANGE_THIS_TO_A_LONG_RANDOM_SECRET}
    expiration-ms: ${APP_JWT_EXPIRATION_MS:86400000}
  sso:
    enabled: false
    frontend-success-uri: http://127.0.0.1:5173/
