spring:
  application:
    name: fms

  datasource:
    url: jdbc:postgresql://localhost:5432/fms_dev
    username: fms
    password: fmspass

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

server:
  port: 8080

app:
  jwt:
    secret: "CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_CHANGE_THIS_TO_A_LONG_RANDOM_SECRET"
    expiration-ms: 86400000